spring:
  liquibase:
    change-log: classpath:/db/changelog.yml
    contexts: prod
  application:
    name: cwa-quick-test-backend
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:quicktest
    username: sa
    password: ''
  archive-datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:quicktest-archive
    username: sa
    password: ''

cwa-testresult-server:
  url: http://localhost:1234

keycloak:
  auth-server-url:
  realm: c19quicktest
  resource: quick-test-portal
  public-client: true
  bearer-only: true

server:
  port: 8093
efgs:
  dbencryption:
    password: m:zteZXp4QPaD?J@f+|'#y;be1fJRXnY
quick-test:
  pointOfCareIdName: poc_id
  tenantIdKey: tenantId
  tenantPointOfCareIdKey: testSpotId
testresultserver:
  enabled: false
  oneWay: false
  twoWay: false
  hostnameVerify: false
  keyStorePath: classpath:keystore.jks
  keyStorePassword: changeit
  trustStorePath: classpath:truststore.jks
  trustStorePassword: changeit
