spring:
  datasource:
    driver-class-name: ${DB_DRIVER_CLASS_NAME}
    url: ${DB_JDBC_URL}
  archive-datasource:
    driver-class-name: ${DB_ARCHIVE_DRIVER_CLASS_NAME}
    url: ${DB_ARCHIVE_JDBC_URL}
  jpa:
    database-platform: ${DB_HIBERNATE_DIALECT}

management:
  server:
    port: 8081
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
      probes:
        enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: info,health,metrics,prometheus
    jmx:
      exposure:
        include: info,health,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true

server:
  ssl:
    key-store-password: ${QUICK_TEST_KEYSTORE_PASSWORD}
    enabled: true
    protocol: TLS
    enabled-protocols: TLSv1.2,TLSv1.3
    ciphers:
      - TLS_AES_128_GCM_SHA256
      - TLS_AES_256_GCM_SHA384
      - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
      - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
      - TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
  error:
    include-stacktrace: never
    include-exception: false
    include-binding-errors: never
    include-message: always
testresultserver:
  enabled: false
  oneWay: false
  twoWay: false
  hostnameVerify: false
  keyStorePassword: ${QUICK_TEST_KEYSTORE_PASSWORD}
  trustStorePassword: ${QUICK_TEST_TRUSTSTORE_PASSWORD}

