spring:
  jpa:
    database-platform: ${DB_HIBERNATE_DIALECT}
  mail:
    host: ${SMTP_SERVER_HOST}
    port: ${SMTP_SERVER_PORT}
    username: ${SMTP_SERVER_USERNAME}
    password: ${SMTP_SERVER_PASSWORD}
    from: ${SMTP_SERVER_FROM}
    test-connection: false
    protocol: smtp
    properties:
      "[mail.smtp.auth]": true
      "[mail.smtp.starttls.enable]": true
      "[mail.smtp.starttls.required]": true

jdbc:
  min-pool: 20
  max-pool: 33
  master:
    driver-class-name: ${DB_DRIVER_CLASS_NAME}
    url: ${DB_JDBC_URL}
    liquibase:
      change-log: classpath:db/changelog.yml
  replica:
    driver-class-name: ${DB_DRIVER_CLASS_NAME}
    url: ${DB_JDBC_URL_READ}
  archive:
    driver-class-name: ${DB_DRIVER_CLASS_NAME}
    url: ${DB_ARCHIVE_JDBC_URL}
    liquibase:
      change-log: classpath:db/archive-changelog.yml

management:
  server:
    port: 8081
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
      probes:
        enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: info,health,metrics,prometheus
    jmx:
      exposure:
        include: info,health,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
  health:
    mail:
      enabled: off

keycloak-admin:
  auth-server-url: ${KEYCLOAK_AUTH-SERVER-URL}
  realm: ${KEYCLOAK_ADMIN_REALM}
  resource: ${KEYCLOAK_ADMIN_RESOURCE}
  credentials:
    secret: ${KEYCLOAK_ADMIN_SECRET}
keycloak-map:
  auth-server-url: ${KEYCLOAK_MAP_AUTH-SERVER-URL}
  realm: ${KEYCLOAK_MAP_REALM}
  resource: ${KEYCLOAK_MAP_RESOURCE}
  credentials:
    username: ${KEYCLOAK_MAP_USERNAME}
    password: ${KEYCLOAK_MAP_PASSWORD}

server:
  ssl:
    key-store-password: ${QUICK_TEST_KEYSTORE_PASSWORD}
    enabled: true
    protocol: TLS
    enabled-protocols: TLSv1.2+TLSv1.3
    ciphers:
      - TLS_AES_128_GCM_SHA256
      - TLS_AES_256_GCM_SHA384
      - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
      - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
      - TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
  error:
    include-stacktrace: never
    include-exception: false
    include-binding-errors: never
    include-message: never

testresultserver:
  enabled: false
  oneWay: false
  twoWay: false
  hostnameVerify: false
  keyStorePassword: ${QUICK_TEST_KEYSTORE_TRS_PASSWORD}
  trustStorePassword: ${QUICK_TEST_TRUSTSTORE_PASSWORD}

testresultserverpcr:
  enabled: false
  oneWay: false
  twoWay: false
  hostnameVerify: false
  keyStorePassword: ${QUICK_TEST_KEYSTORE_TRS_PASSWORD}
  trustStorePassword: ${QUICK_TEST_TRUSTSTORE_PASSWORD}

mapserver:
  enabled: false
  oneWay: false
  twoWay: false
  hostnameVerify: false
  keyStorePassword: ${QUICK_TEST_KEYSTORE_MAP_PASSWORD}
  trustStorePassword: ${QUICK_TEST_TRUSTSTORE_PASSWORD}

quicktest-map-server:
  url: ${QUICK_TEST_MAP_SERVER_URL}

dccserver:
  enabled: false
  oneWay: false
  twoWay: false
  hostnameVerify: false
  keyStorePassword: ${DCC_KEYSTORE_PASSWORD}
  trustStorePassword: ${DCC_TRUSTSTORE_PASSWORD}

quicktest:
  db-encryption-key: ${QUICK_TEST_DB_ENCRYPTION_PASSWORD}
  clean-up-settings:
    cron: 0 0 0 * * *
    max-age-in-minutes: 3600
    locklimit: 1800000
  frontend-context-config:
    rules-server-url: ${QUICK_TEST_DCC_RULES_SERVER_URL}
    environment-name: ${QUICK_TEST_ENVIRONMENT_NAME:unknown}
  cancellation:
    final-deletion-days: ${QUICK_TEST_CANCELLATION_FINAL_DELETION_DAYS:28}

archive:
  excluded-partners: ${QT_ARCHIVE_EXCLUDED_PARTNERS:}
  moveToArchiveJob:
    cron: ${QT_ARCHIVE_JOB_CRON:0 0/5 * * * *}
    locklimit: 1800000
    older-than-in-seconds: ${QT_ARCHIVE_JOB_OLDER_THAN_IN_SECONDS:1209600}
    chunkSize: ${QT_ARCHIVE_JOB_CHUNK_SIZE:100}
  cancellationArchiveJob:
    cron: ${QT_CANCELLATION_ARCHIVE_JOB_CRON:0 0/5 * * * *}
    locklimit: 1800000
    chunkSize: ${QT_CANCELLATION_ARCHIVE_JOB_CHUNK_SIZE:100}
  cancellationSearchPortalDeleteJob:
    cron: ${QT_CANCELLATION_SEARCH_PORTAL_DELETE_JOB_CRON:0 0/5 * * * *}
    locklimit: 1800000
    chunkSize: ${QT_CANCELLATION_SEARCH_PORTAL_JOB_CHUNK_SIZE:100}
  csvUploadJob:
    cron: ${QT_CANCELLATION_UPLOAD_JOB_CRON:0 0/5 * * * *}
    locklimit: 1800000
    chunkSize: ${QT_CANCELLATION_UPLOAD_JOB_CHUNK_SIZE:100}
  hash:
    algorithm: SHA-256
    pepper: ${QT_ARCHIVE_PEPPER:APKzWUszQftHMN5xP9m3E96hCy4znGv7k3Na5zZUHfYgbExCCn}
  crypt:
    secretLength: 50
    secretLetters: true
    secretNumbers: true
    defaultRsa: RSA/ECB/OAEPwithSHA-512andMGF1Padding
    defaultAes: AES/GCM/NoPadding
    AesGcmNoPadding256:
      iterations: ${QT_ARCHIVE_ITERATIONS:128}
  vaultTransit:
    folder: ${QT_VAULT_FOLDER:cwa-quick-test-archive}
    dek: ${QT_VAULT_DEK:cwa-quick-test-archive-encryption-key}

cancellation:
  finalDeleteJob:
    cron: ${QT_CANCELLATION_FINAL_DELETE_JOB_CRON:0 0/5 * * * *}
    locklimit: 1800000
  completePendingTestsHours: ${QT_CANCELLATION_COMPLETE_PENDING_TESTS_HOURS:24}
  readyToArchiveHours: ${QT_CANCELLATION_READY_TO_ARCHIVE_HOURS:48}

s3:
  accessKey: ${S3_ACCESS_KEY}
  bucketName: ${S3_BUCKET_NAME}
  proxy:
    enabled: false
    host:
    port: -1
  region:
    endpoint: ${S3_REGION_ENDPOINT}
    name: ${S3_REGION_NAME}
  secretKey: ${S3_SECRET_KEY}
  expiration: 3600
