spring:
  datasource:
    driver-class-name: ${DB_DRIVER_CLASS_NAME}
    url: ${DB_JDBC_URL}
  archive-datasource:
    driver-class-name: ${DB_ARCHIVE_DRIVER_CLASS_NAME}
    url: ${DB_ARCHIVE_JDBC_URL}
  jpa:
    database-platform: ${DB_HIBERNATE_DIALECT}
  mail:
    host: ${SMTP_SERVER_HOST}
    port: ${SMTP_SERVER_PORT}
    username: ${SMTP_SERVER_USERNAME}
    password: ${SMTP_SERVER_PASSWORD}
    from: ${SMTP_SERVER_FROM}
    test-connection: false
    protocol: smtp
    properties:
      "[mail.smtp.auth]": true
      "[mail.smtp.starttls.enable]": true
      "[mail.smtp.starttls.required]": true

management:
  server:
    port: 8081
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
      probes:
        enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: info,health,metrics,prometheus
    jmx:
      exposure:
        include: info,health,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
  health:
    mail:
      enabled: off

server:
  ssl:
    key-store-password: ${QUICK_TEST_KEYSTORE_PASSWORD}
    enabled: true
    protocol: TLS
    enabled-protocols: TLSv1.2,TLSv1.3
    ciphers:
      - TLS_AES_128_GCM_SHA256
      - TLS_AES_256_GCM_SHA384
      - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
      - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
      - TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
  error:
    include-stacktrace: never
    include-exception: false
    include-binding-errors: never
    include-message: never

testresultserver:
  enabled: false
  oneWay: false
  twoWay: false
  hostnameVerify: false
  keyStorePassword: ${QUICK_TEST_KEYSTORE_TRS_PASSWORD}
  trustStorePassword: ${QUICK_TEST_TRUSTSTORE_PASSWORD}

quicktest:
  db-encryption-key: ${QUICK_TEST_DB_ENCRYPTION_PASSWORD}
  clean-up-settings:
    cron: 0 0 0 * * *
    max-age-in-minutes: 3600
    locklimit: 1800000

cwa:
  dcc:
    verification-server:
      enable-mtls: true
      base-url: ${CWA_DCC_VERIFICATIONSERVER_BASEURL}
      key-store-path: ${CWA_DCC_VERIFICATIONSERVER_KEYSTOREPATH}
      key-store-password: ${CWA_DCC_VERIFICATIONSERVER_KEYSTOREPASSWORD}
      trust-store-path: ${CWA_DCC_VERIFICATIONSERVER_TRUSTSTOREPATH}
      trust-store-password: ${CWA_DCC_VERIFICATIONSERVER_TRUSTSTOREPASSWORD}
      verify-hostnames: false
    signing-api-server:
      enable-mtls: true
      base-url: ${CWA_DCC_SIGNINGAPISERVER_BASEURL}
      key-store-path: ${CWA_DCC_SIGNINGAPISERVER_KEYSTOREPATH}
      key-store-password: ${CWA_DCC_SIGNINGAPISERVER_KEYSTOREPASSWORD}
      trust-store-password: ${CWA_DCC_SIGNINGAPISERVER_TRUSTSTOREPASSWORD}
      trust-store-path: ${CWA_DCC_SIGNINGAPISERVER_TRUSTSTOREPATH}
      api-key: ${CWA_DCC_SIGNINGAPISERVER_APIKEY}
      verify-hostnames: true
    request:
      sizelimit: 10000
    entities:
      cleanup:
        days: 21
        rate: 1800000
