spring:
  h2:
    console:
      enabled: true
      path: '/h2-console'
  liquibase:
    change-log: classpath:/db/changelog.yml
  application:
    name: cwa-quick-test-backend
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:log
    username: sa
    password: ''

cwa-testresult-server:
  url: http://localhost:1234

keycloak:
  auth-server-url: https://quicktest-iam-6155b8d7d3c6.coronawarn.app/auth/
  realm: c19quicktest
  resource: quick-test-portal
  public-client: true
  bearer-only: true
  proxy-url: http://sia-lb.telekom.de:8080

server:
  port: 8093
quick-test:
  testSpotIdName: poc_id
  tenantIdKey: tenantId
  tenantSpotIdKey: testSpotId
testresultserver:
  enabled: false
  oneWay: false
  twoWay: false
  hostnameVerify: false
  keyStorePath: classpath:keystore.jks
  keyStorePassword: changeit
  trustStorePath: classpath:truststore.jks
  trustStorePassword: changeit
