spring:
  datasource:
    driver-class-name: ${DB_DRIVER_CLASS_NAME}
    url: ${DB_JDBC_URL}
  archive-datasource:
    driver-class-name: ${DB_ARCHIVE_DRIVER_CLASS_NAME}
    url: ${DB_ARCHIVE_JDBC_URL}
  jpa:
    database-platform: ${DB_HIBERNATE_DIALECT}
  mail:
    host: ${SMTP_SERVER_HOST}
    port: ${SMTP_SERVER_PORT}
    username: ${SMTP_SERVER_USERNAME}
    password: ${SMTP_SERVER_PASSWORD}
    from: ${SMTP_SERVER_FROM}
    test-connection: false
    protocol: smtp
    properties:
      "[mail.smtp.auth]": true
      "[mail.smtp.starttls.enable]": true
      "[mail.smtp.starttls.required]": true

management:
  server:
    port: 8081
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
      probes:
        enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: info,health,metrics,prometheus
    jmx:
      exposure:
        include: info,health,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
  health:
    mail:
      enabled: off

server:
  ssl:
    key-store-password: ${QUICK_TEST_KEYSTORE_PASSWORD}
    enabled: true
    protocol: TLS
    enabled-protocols: TLSv1.2,TLSv1.3
    ciphers:
      - TLS_AES_128_GCM_SHA256
      - TLS_AES_256_GCM_SHA384
      - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
      - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
      - TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
  error:
    include-stacktrace: never
    include-exception: false
    include-binding-errors: never
    include-message: never

testresultserver:
  enabled: false
  oneWay: false
  twoWay: false
  hostnameVerify: false
  keyStorePassword: ${QUICK_TEST_KEYSTORE_TRS_PASSWORD}
  trustStorePassword: ${QUICK_TEST_TRUSTSTORE_PASSWORD}

dccserver:
  enabled: false
  oneWay: false
  twoWay: false
  hostnameVerify: false
  keyStorePassword: ${DCC_KEYSTORE_PASSWORD}
  trustStorePassword: ${DCC_TRUSTSTORE_PASSWORD}

quicktest:
  db-encryption-key: ${QUICK_TEST_DB_ENCRYPTION_PASSWORD}
  health-department-download-url: ${HEALTH_DEPARTMENT_DOWNLOAD_URL}
  health-department-download-cron: 0 0 0 */2 * *
  clean-up-settings:
    cron: 0 0 0 * * *
    max-age-in-minutes: 3600
    locklimit: 1800000

email:
  tested-person:
    enabled: ${EMAIL_NOTIFICATION_TO_TP_ENABLED}
    subject: "Das Ergebnis Ihres Covid-19 Antigen-Schnelltests liegt vor."
    title-text: "Guten Tag "
    text: "</br></br>im Anhang erhalten Sie das Ergebnis Ihres Covid-19 Antigen-Schnelltests.</br>
           Bitte lesen Sie die Hinweise im Dokument sorgfältig und halten Sie sich an die beschriebenen Regeln.</br>
           Das gilt insbesondere, wenn Ihr Ergebnis positiv sein sollte. </br></br>
           Mit freundlichen Grüßen </br>
           Ihr Testzentrum"
    attachment-filename: "Schnelltestergebnis.pdf"
  health-department:
    enabled: ${EMAIL_NOTIFICATION_TO_HD_ENABLED}
    subject: "Positives Ergebnis eines Covid-19 Antigen-Schnelltests"
    text: "Sehr geehrte Damen und Herren, </br></br> im Anhang erhalten Sie die Daten zu einer Testperson,
          deren Antigen-Schnelltest auf Covid-19 in unserer Teststelle positiv ausgefallen ist. </br></br>
          Mit freundlichen Grüßen </br>
          Ihr Testzentrum"
    attachment-filename: ""

