spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRESQL_SERVICE_HOST}:${POSTGRESQL_SERVICE_PORT}/${POSTGRESQL_DATABASE}
    username: ${POSTGRESQL_USER}
    password: ${POSTGRESQL_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

management:
  server:
    port: 8081
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
      probes:
        enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: info,health,metrics,prometheus
    jmx:
      exposure:
        include: info,health,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true

server:
  ssl:
    key-store-password: ${QUICK_TEST_KEYSTORE_PASSWORD}
    enabled: true
    protocol: TLS
    enabled-protocols: TLSv1.2,TLSv1.3
    ciphers:
      - TLS_AES_128_GCM_SHA256
      - TLS_AES_256_GCM_SHA384
      - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
      - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
      - TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
testresultserver:
  enabled: false
  oneWay: false
  twoWay: false
  hostnameVerify: false
  keyStorePassword: ${QUICK_TEST_KEYSTORE_PASSWORD}
  trustStorePassword: ${QUICK_TEST_TRUSTSTORE_PASSWORD}