spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  liquibase:
    change-log: classpath:/db/changelog.yml
    contexts: prod
  application:
    name: cwa-quick-test-backend
  jpa:
    database: mysql
    hibernate:
      ddl-auto: validate
  archive-datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:quicktest-archive;MODE=MYSQL
    username: sa
    password: ''
  mail:
    host:
    port:
    username:
    password:
    from:
    test-connection: false
    protocol: smtp
    properties:
      "[mail.smtp.auth]": true
      "[mail.smtp.starttls.enable]": true
      "[mail.smtp.starttls.required]": true
      "[mail.smtp.ssl.trust]": "*"

jdbc:
  min-pool: 15
  max-pool: 25
  master:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:quicktest;MODE=MYSQL
    liquibase:
      change-log: classpath:db/changelog.yml
  replica:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:quicktest;MODE=MYSQL
  archive:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:quicktest-archive;MODE=MYSQL
    liquibase:
      change-log: classpath:db/archive-changelog.yml

logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSSXXX, UTC

cwa-testresult-server:
  url: http://localhost:8080
  url-pcr: http://localhost:8081

keycloak:
  auth-server-url:
  realm:
  resource: quick-test-portal
  public-client: true
  bearer-only: true


keycloak-admin:
  auth-server-url:
  realm:
  resource:
  credentials:
    secret:

keycloak-map:
  auth-server-url: http://localhost:8080
  realm: dummy
  resource: dummy
  credentials:
    username: dummy
    password: dummy

server:
  port: 8093
  error:
    include-stacktrace: always
    include-exception: true
    include-binding-errors: always
    include-message: always

quicktest:
  pointOfCareIdName: poc_id
  tenantIdKey: tenantId
  groupKey: groups
  bsnrKey: bsnr
  pcrEnabledKey: pcr_enabled
  tenantPointOfCareIdKey: pocId
  pointOfCareInformationName: poc_details
  pointOfCareInformationDelimiter: \,
  groupInformationDelimiter: \,
  db-encryption-key: abcdefghjklmnopq
  labId: labId4711
  clean-up-settings:
    cron: 0 * * * * *
    max-age-in-minutes: 1440
    locklimit: 1800000
    chunkSize: 1000
  frontend-context-config:
    rules-server-url: https://distribution-6155b8d7d3c6.dcc-rules.de
    environment-name: local

archive:
  jks:
    path: classpath:archive/dev.jks
    password: changeMe
  moveToArchiveJob:
    cron: "-"
    locklimit: 1800000
    #### 1209600 = 2 weeks
    older-than-in-seconds: 5000
  hash:
    algorithm: SHA-256
    pepper: APKzWUszQftHMN5xP9m3E96hCy4znGv7k3Na5zZUHfYgbExCCn
  crypt:
    secretLength: 50
    secretLetters: true
    secretNumbers: true
    defaultRsa: RSA/ECB/OAEPwithSHA-512andMGF1Padding
    defaultAes: AES/GCM/NoPadding
    AesGcmNoPadding256:
      iterations: 12345

testresultserver:
  enabled: false
  oneWay: false
  twoWay: false
  hostnameVerify: false
  keyStorePath: classpath:keystore.jks
  keyStorePassword: changeit
  trustStorePath: classpath:truststore.jks
  trustStorePassword: changeit

testresultserverpcr:
  enabled: false
  oneWay: false
  twoWay: false
  hostnameVerify: false
  keyStorePath: classpath:keystore.jks
  keyStorePassword: changeit
  trustStorePath: classpath:truststore.jks
  trustStorePassword: changeit

mapserver:
  enabled: false
  oneWay: false
  twoWay: false
  hostnameVerify: false
  keyStorePath: classpath:keystore.jks
  keyStorePassword: changeit
  trustStorePath: classpath:truststore.jks
  trustStorePassword: changeit

management:
  health:
    mail:
      enabled: off

auditlogs:
  pattern: "User: {}; tenantId: {}; pocID: {}; action: {}; Object: {}; ID: {}"

pdf:
  signatureText: "Dieses Schreiben wurde maschinell erstellt und bedarf keiner Unterschrift."
  positiveInstructionText: "Sie sind mit hoher Wahrscheinlichkeit mit dem SARS-CoV-2 Virus infiziert. Begeben Sie sich bitte unverzüglich in die häusliche Quarantäne und informieren Sie Hausstandsangehörige und weitere nahe Kontaktpersonen. Kontaktieren Sie umgehend Ihren Hausarzt oder die Leitstelle des Ärztlichen Bereitschaftsdienstes unter der Nummern 116117 für weitere Verhaltensregeln und zur nun benötigten Durchführung eines PCR-Tests."
  negativeInstructionText: "Bitte beachten Sie, dass ein negatives Ergebnis eine mögliche Infektion nicht vollständig ausschließen kann und lediglich eine Momentaufnahme darstellt."
  testBrandNameDescriptionText: "Handelsname: "
  tradeNameEmptyText: "nicht angegeben"
  testBrandIdDescriptionText: "Test-ID: "
  quickTestHeadlineText: "Corona-Antigen-Schnelltest"
  authorPdfPropertiesText: "Schnelltestportal"
  creatorPdfPropertiesText: "Schnelltestportal"
  personPhoneDescriptionText: "Tel.: "
  logoPath: "logo.png"
  quickTestOfDateText: "Schnelltestergebnis vom "
  personEmailDescriptionText: "E-mail: "
  testResultDescriptionText: "Testergebnis: "
  testResultPendingText: "ausstehend"
  testResultNegativeText: "negativ (Zum Zeitpunkt des Tests wurde keine Infektion mit dem SARS-CoV-2 Virus festgestellt)."
  testResultPositiveText: "positiv"
  testResultDefaultText: "fehlgeschlagen"
  executedByDescriptionText: "Durchgeführt: "
  furtherDataAboutThePersonText: "Weitere Angaben zur Person: "
  genderDescriptionText: "Geschlecht: "
  maleText: "männlich"
  femaleText: "weiblich"
  diverseText: "divers"
  birthDateDescriptionText: "Geburtstag: "
  furtherDataAboutTestDescriptionText: "Weitere Angaben zum Test: "
  executedFromDescriptionText: "Durchgeführt durch: "

dccserver:
  enabled: false
  oneWay: false
  twoWay: false
  hostnameVerify: false
  keyStorePath: classpath:keystore.jks
  keyStorePassword: changeit
  trustStorePath: classpath:truststore.jks
  trustStorePassword: changeit

quicktest-map-server:
  url: http://localhost:9999

cwa-dcc-server:
  url: http://localhost:8080

dcc:
  algId: -7
  country: DE
  issuer: RKI
  cwtIssuer: DE
  expired: 354
  searchPublicKeysJob:
    fixedDelayString: 30000
    lockLimit: 1800000
  uploadDccJob:
    fixedDelayString: 30000
    lockLimit: 1800000
