spring:
  liquibase:
    change-log: classpath:/db/changelog.yml
    contexts: prod
  application:
    name: cwa-quick-test-backend
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:quicktest;MODE=MYSQL
    username: sa
    password: ''
  archive-datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:quicktest-archive;MODE=MYSQL
    username: sa
    password: ''
  mail:
    host:
    port:
    username:
    password:
    from:
    test-connection: false
    protocol: smtp
    properties:
      "[mail.smtp.auth]": true
      "[mail.smtp.starttls.enable]": true
      "[mail.smtp.starttls.required]": true

logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSSXXX, UTC

cwa-testresult-server:
  url: http://localhost:8080

keycloak:
  auth-server-url:
  realm:
  resource: quick-test-portal
  public-client: true
  bearer-only: true

server:
  port: 8093
  error:
    include-stacktrace: always
    include-exception: true
    include-binding-errors: always
    include-message: always

quicktest:
  pointOfCareIdName: poc_id
  tenantIdKey: tenantId
  tenantPointOfCareIdKey: pocId
  pointOfCareInformationName: poc_details
  pointOfCareInformationDelimiter: \,
  point-of-care-zipcode-key: postal_code
  db-encryption-key: abcdefghjklmnopq
  labId: labId4711
  health-department-download-url:
  health-department-download-cron: 0 */2 * * * *
  clean-up-settings:
    cron: 0 * * * * *
    max-age-in-minutes: 2
    locklimit: 1800000

testresultserver:
  enabled: false
  oneWay: false
  twoWay: false
  hostnameVerify: false
  keyStorePath: classpath:keystore.jks
  keyStorePassword: changeit
  trustStorePath: classpath:truststore.jks
  trustStorePassword: changeit

management:
  health:
    mail:
      enabled: off

auditlogs:
  pattern: "User: {}; tenantId: {}; pocID: {}; action: {}; Object: {}; ID: {}"

pdf:
  signatureText: "Dieses Schreiben wurde maschinell erstellt und bedarf keiner Unterschrift."
  positiveInstructionText: "Ihr Antigen-Schnelltests ist positiv ausgefallen, begeben Sie sich bitte unverzüglich in die häusliche Quarantäne und informieren Sie Hausstandsangehörige und weitere nahe Kontaktpersonen. Kontaktieren Sie umgehend Ihren Hausarzt oder die Leitstelle des Ärztlichen Bereitschaftsdienstes unter der Nummern 116117 für weitere Verhaltensregeln und zur nun benötigten Durchführung eines PCR-Tests."
  negativeInstructionText: "Bitte beachten Sie, dass ein negatives Ergebnis eine mögliche Infektion nicht vollständig ausschließen kann und lediglich eine Momentaufnahme darstellt."
  testBrandNameDescriptionText: "Handelsname: "
  tradeNameEmptyText: "nicht angegeben"
  testBrandIdDescriptionText: "Test-ID: "
  quickTestHeadlineText: "Corona-Antigen-Schnelltest"
  authorPdfPropertiesText: "Schnelltestportal"
  creatorPdfPropertiesText: "Schnelltestportal"
  personPhoneDescriptionText: "Tel.: "
  logoPath: "logo.png"
  quickTestOfDateText: "Schnelltestergebnis vom "
  personEmailDescriptionText: "E-mail: "
  testResultDescriptionText: "Testergebnis: "
  testResultPendingText: "ausstehend"
  testResultNegativeText: "negativ"
  testResultPositiveText: "positiv"
  testResultDefaultText: "fehlgeschlagen"
  executedByDescriptionText: "Durchgeführt: "
  furtherDataAboutThePersonText: "Weitere Angaben zu der Person: "
  genderDescriptionText: "Geschlecht: "
  maleText: "männlich"
  femaleText: "weiblich"
  diverseText: "divers"
  birthDateDescriptionText: "Geburtstag: "
  furtherDataAboutTestDescriptionText: "Weitere Angaben zum Test: "
  executedFromDescriptionText: "Durchgeführt durch: "

dccserver:
  enabled: false
  oneWay: false
  twoWay: false
  hostnameVerify: false
  keyStorePath: classpath:keystore.jks
  keyStorePassword: changeit
  trustStorePath: classpath:truststore.jks
  trustStorePassword: changeit

cwa-dcc-server:
  url: http://localhost:8080

dcc:
  algId: -7
  issuer: DE
  expired: 354
  searchPublicKeysJob:
    fixedDelayString: 30000
    lockLimit: 1800000
  uploadDccJob:
    fixedDelayString: 30000
    lockLimit: 1800000

email:
  tested-person:
    enabled: false
    subject: "Das Ergebnis Ihres Covid-19 Antigen-Schnelltests liegt vor."
    title-text: "Guten Tag "
    text: "</br></br>im Anhang erhalten Sie das Ergebnis Ihres Covid-19 Antigen-Schnelltests.</br>
           Bitte lesen Sie die Hinweise im Dokument sorgfältig und halten Sie sich an die beschriebenen Regeln.</br>
           Das gilt insbesondere, wenn Ihr Ergebnis positiv sein sollte. </br></br>
           Mit freundlichen Grüßen </br>
           Ihr Testzentrum"
    attachment-filename: "Schnelltestergebnis.pdf"
  health-department:
    enabled: false
    subject: "Positives Ergebnis eines Covid-19 Antigen-Schnelltests"
    text: "Sehr geehrte Damen und Herren, </br></br> im Anhang erhalten Sie die Daten zu einer Testperson,
          deren Antigen-Schnelltest auf Covid-19 in unserer Teststelle positiv ausgefallen ist. </br></br>
          Mit freundlichen Grüßen </br>
          Ihr Testzentrum"
    attachment-filename: ""

otc-sms-server:
  url:
sms:
  enabled: false
  passwordLength: 6
  messageTemplate: "Das Passwort für Ihr Testergebnis lautet: %s"