name: ci-env
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: environment
      run: |
        APP_SHA=$(git rev-parse --short ${GITHUB_SHA})
        echo "APP_SHA=${APP_SHA}" >> ${GITHUB_ENV}
        APP_REV=$(git rev-list --tags --max-count=1)
        echo "APP_REV=${APP_REV}" >> ${GITHUB_ENV}
        APP_TAG=$(git describe --tags ${APP_REV} 2> /dev/null || echo 0.0.0)
        echo "APP_TAG=${APP_TAG}" >> ${GITHUB_ENV}
        VERSION=${APP_TAG}-${APP_SHA}
        echo "VERSION=${VERSION}" >> ${GITHUB_ENV};