name: ci-pull-request
on:
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker build
      run: echo ${APP_PACKAGES_USERNAME} && docker build
        --build-arg MAVEN_PASSWORD=${{ secret.GITHUB_TOKEN }}
        --build-arg MAVEN_USERNAME=cwa
        .
