name: ci-pull-request
on:
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker build
      run: docker build
        --build-arg MAVEN_PASSWORD=${APP_PACKAGES_PASSWORD}
        --build-arg MAVEN_USERNAME=${APP_PACKAGES_USERNAME}
        .
      env:
        APP_PACKAGES_USERNAME: ${{ github.actor }}
        APP_PACKAGES_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
